```mermaid
graph TD
    BridgeGenerator --> BridgeGeneratorEditor
    ActivateMirror --> BorderColor
    ActivateMirror --> BotellaLab
    ActivateMirror --> CottonBehabiour
    ActivateMirror --> HapticFeedback
    ActivateMirror --> IsLiquidSource
    ActivateMirror --> ProbeBehabiour
    ActivateMirror --> ProbetaSnap
    ActivateMirror --> PulidoraScript
    AugmentsBehabiour --> MicroscopeBehabiour
    BorderColor --> ProbeBehabiour
    BoteBasura --> LijaCircularBehabiour
    BotellaLab --> IsLiquidSource
    CubreLijaBehabiour --> LijaRotation
    CubreLijaSnap --> CubreLijaBehabiour
    DetectParticleCollision --> ActivateMirror
    DetectParticleCollision --> BotellaLab
    DetectParticleCollision --> IsLiquidSource
    EjectObject --> Ejectable
    EjectObject --> LijaRotation
    EjectObject --> PulidoraScript
    HapticFeedback --> ProbeBehabiour
    IdentifyFace --> LijaCircularBehabiour
    IdentifyFace --> ProbeBehabiour
    IdentifyFace --> PulidoraScript
    InteractProbe --> UpdatePreview
    IsProbeTouched --> ProbeBehabiour
    LijaCircularBehabiour --> BotellaLab
    LijaCircularBehabiour --> LijaDataholder
    LijaCircularBehabiour --> LijaRotation
    LijaCuadrada --> EventCallerOnHoldOnDrop
    LijaCuadrada --> LijaCircularBehabiour
    LijaCuadrada --> LijaDataholder
    LijaCuadrada --> TijerasBehabiour
    LijaRotation --> CubreLijaSnap
    LijaRotation --> LijaCircularBehabiour
    MicroscopeBehabiour --> ActivateMirror
    MicroscopeBehabiour --> ElementType
    MicroscopeBehabiour --> MicroscopeElements
    MicroscopeBehabiour --> ProbeBehabiour
    MicroscopeElements --> ElementType
    ObjectSnapBehabiour --> placeable
    PistolaDeCalor --> ActivateMirror
    PistolaDeCalor --> Heatable
    ProbeBehabiour --> BorderColor
    ProbeBehabiour --> HapticFeedback
    ProbeBehabiour --> InteractProbe
    ProbeBehabiour --> LijaCircularBehabiour
    ProbeBehabiour --> LijaRotation
    ProbeBehabiour --> PulidoraScript
    ProbetaSnap --> InteractProbe
    ProbetaSnap --> ProbeBehabiour
    PulidoraScript --> BotellaLab
    SnowParticlePooll --> SnowParticleFollowPlayer
    TriggerPulidora --> ActivateMirror
    UpdatePreview --> BorderColor
    InteractToggle --> that
    PlayerModSetter --> allows
    GlobalToggleObject --> that
    GlobalToggleObject --> allows
```
