```mermaid
graph TD
    DependencyDiagramGenerator --> |variable| string
    ReflectionDependencyDiagramGenerator --> |variable| string
    RoslynDependencyDiagramGenerator --> |variable| string
    BridgeGenerator --> |variable| GameObject[]
    BridgeGenerator --> |variable| GameObject
    BridgeGenerator --> |variable| Mesh
    BridgeGenerator --> |variable| Vector3
    BridgeGenerator --> |variable| float
    ActivateMirror --> |variable| GameObject
    ActivateMirror --> |variable| ProbeBehabiour
    ActivateMirror --> |variable| VRC_Pickup
    ActivateMirror --> |variable| float
    ActivateMirror --> |variable| bool
    ActivateMirror --> |variable| PulidoraScript
    ActivateMirror --> |variable| ParticleSystem
    ActivateMirror --> |variable| VRCMirrorReflection
    ActivateMirror --> |variable| LayerMask
    ActivateParticlesOnPickupUse --> |variable| VRC_Pickup
    ActivateParticlesOnPickupUse --> |variable| MeshRenderer
    ActivateParticlesOnPickupUse --> |variable| ParticleSystem
    ActivateParticlesOnPickupUse --> |variable| Transform
    ActivateParticlesOnPickupUse --> |variable| bool
    ActivateParticlesOnTilt --> |variable| VRC_Pickup
    ActivateParticlesOnTilt --> |variable| MeshRenderer
    ActivateParticlesOnTilt --> |variable| ParticleSystem
    ActivateParticlesOnTilt --> |variable| Transform
    AugmentsBehabiour --> |variable| int
    AugmentsBehabiour --> |variable| MicroscopeBehabiour
    AugmentsBehabiour --> |variable| GameObject
    AugmentsBehabiour --> |variable| AudioSource
    AugmentsBehabiour --> |variable| AudioClip
    BorderColor --> |variable| GameObject
    BorderColor --> |variable| float
    BorderColor --> |variable| bool
    BotellaLab --> |variable| float
    BotellaLab --> |variable| bool
    BotellaLab --> |variable| string
    BotellaLab --> |variable| GameObject
    BotellaLab --> |variable| Material
    BotellaLab --> |variable| VRC_Pickup
    BotellaLab --> |variable| MeshRenderer
    BotellaLab --> |variable| ParticleSystem
    BotellaLab --> |variable| Vector3
    BotellaLab --> |variable| Transform
    ButtonInteraction3D --> |variable| Rigidbody
    ButtonInteraction3D --> |variable| ConfigurableJoint
    ButtonInteraction3D --> |variable| UdonBehaviour
    ButtonInteraction3D --> |variable| float
    ButtonInteraction3D --> |variable| Vector3
    ButtonInteraction3D --> |variable| string
    ButtonInteraction3D --> |variable| bool
    CallerTest --> |variable| int
    CallerTest --> |variable| Material[]
    CallerTest --> |variable| MeshRenderer
    Cheto --> |variable| bool
    Cheto --> |variable| Transform
    Cheto --> |variable| ParticleSystem
    Cheto --> |variable| AudioSource
    CottonBehabiour --> |variable| Material
    CubreLijaBehabiour --> |variable| GameObject
    CubreLijaBehabiour --> |variable| LijaRotation
    CubreLijaSnap --> |variable| bool
    CubreLijaSnap --> |variable| GameObject
    CubreLijaSnap --> |variable| VRC_Pickup
    DetectParticleCollision --> |variable| ActivateMirror
    DirSelectorScript --> |variable| VRC_Pickup
    DirSelectorScript --> |variable| Transform
    DoorHandleInteraction --> |variable| VRC_Pickup
    DoorHandleInteraction --> |variable| Vector3[]
    DoorHandleInteraction --> |variable| Transform
    DoorHandleInteraction --> |variable| GameObject
    DoorHandleInteraction --> |variable| bool
    DoorInteraction --> |variable| VRC_Pickup
    DoorInteraction --> |variable| Rigidbody
    DoorInteraction --> |variable| GameObject
    DoorInteraction --> |variable| GameObject[]
    DoorInteraction --> |variable| bool
    DoorInteraction --> |variable| float
    EjectObject --> |variable| GameObject
    EjectObject --> |variable| VRC_Pickup
    EjectObject --> |variable| Vector3
    ElementType --> |variable| string
    ElementType --> |variable| IUdonEventReceiver
    ElementType --> |variable| VRCUrl[]
    ElementType --> |variable| IVRCImageDownload[]
    EventCallerOnHoldOnDrop --> |variable| GameObject[]
    EventCallerOnHoldOnDrop --> |variable| UdonBehaviour[]
    EventCallerOnHoldOnDrop --> |variable| string[]
    GoToHandVR --> |variable| Transform
    GoToHandVR --> |variable| bool[]
    GoToHandVR --> |variable| bool
    GoToHandVR --> |variable| VRCPlayerApi
    HapticFeedback --> |variable| VRC_Pickup
    HapticFeedback --> |variable| float
    Heatable --> |variable| UdonBehaviour[]
    Heatable --> |variable| string
    IdentifyFace --> |variable| GameObject
    IdentifyFace --> |variable| ProbeBehabiour
    InteractProbe --> |variable| bool
    InteractProbe --> |variable| GameObject
    IsProbeTouched --> |variable| bool
    IsProbeTouched --> |variable| string
    IsProbeTouched --> |variable| UdonBehaviour
    IsProbeTouched --> |variable| ProbeBehabiour
    LijaCircularBehabiour --> |variable| int
    LijaCircularBehabiour --> |variable| LijaDataholder
    LijaCircularBehabiour --> |variable| float
    LijaCircularBehabiour --> |variable| TextMeshProUGUI
    LijaCircularBehabiour --> |variable| MeshRenderer
    LijaCircularBehabiour --> |variable| Rigidbody
    LijaCuadrada --> |variable| LijaDataholder
    LijaCuadrada --> |variable| GameObject[]
    LijaCuadrada --> |variable| int
    LijaCuadrada --> |variable| TextMeshProUGUI
    LijaCuadrada --> |variable| bool
    LijaCuadrada --> |variable| Rigidbody
    LijaDataholder --> |variable| VRCObjectPool
    LijaDataholder --> |variable| Material[]
    LijaDataholder --> |variable| DataDictionary
    LijaRotation --> |variable| bool
    LijaRotation --> |variable| float
    LijaRotation --> |variable| GameObject
    LijaRotation --> |variable| VRC_Pickup
    LijaRotation --> |variable| TextMeshProUGUI
    LijaRotation --> |variable| AudioSource
    LijaRotation --> |variable| AudioClip
    LijaRotation --> |variable| CubreLijaSnap
    MicroscopeBehabiour --> |variable| Image[]
    MicroscopeBehabiour --> |variable| RawImage[]
    MicroscopeBehabiour --> |variable| TextMeshProUGUI
    MicroscopeBehabiour --> |variable| MicroscopeElements
    MicroscopeBehabiour --> |variable| GameObject
    MicroscopeBehabiour --> |variable| ProbeBehabiour
    MicroscopeBehabiour --> |variable| bool
    MicroscopeBehabiour --> |variable| int
    MicroscopeBehabiour --> |variable| DataDictionary
    MicroscopeElements --> |variable| ElementType[]
    MicroscopeElements --> |variable| Texture2D
    MicroscopeElements --> |variable| VRCImageDownloader
    ObjectSnapBehabiour --> |variable| bool
    ObjectSnapBehabiour --> |variable| Vector3
    ObjectSnapBehabiour --> |variable| float
    ObjectSnapBehabiour --> |variable| GameObject[]
    ObjectSnapBehabiour --> |variable| UdonBehaviour[]
    ObjectSnapBehabiour --> |variable| string[]
    ObjectSnapBehabiour --> |variable| Collider[]
    ObjectSnapBehabiour --> |variable| GameObject
    ObjectSnapBehabiour --> |variable| AudioSource
    ObjectSnapBehabiour --> |variable| AudioClip
    ObjectSnapVisual --> |variable| MeshRenderer
    ObjectSnapVisual --> |variable| MeshFilter
    ObjectSnapVisual --> |variable| Mesh
    ObjectSnapVisual --> |variable| Material
    OnParticleHitChangeVisual --> |variable| MeshRenderer
    PistolaDeCalor --> |variable| CapsuleCollider
    PistolaDeCalor --> |variable| bool
    PistolaDeCalor --> |variable| Animator
    PistolaDeCalor --> |variable| AudioSource
    PistolaDeCalor --> |variable| ParticleSystem
    PistolaDeCalor --> |variable| VRCPickup
    PistolaDeCalor --> |variable| DataDictionary
    PistolaDeCalor --> |variable| AudioClip
    PistolaDeCalor --> |variable| float
    PlayerRespawnController --> |variable| Transform
    PlayerRespawnController --> |variable| ParticleSystem
    ProbeBehabiour --> |variable| float
    ProbeBehabiour --> |variable| int
    ProbeBehabiour --> |variable| Vector3
    ProbeBehabiour --> |variable| Material
    ProbeBehabiour --> |variable| ParticleSystem
    ProbeBehabiour --> |variable| GameObject
    ProbeBehabiour --> |variable| LijaRotation
    ProbeBehabiour --> |variable| VRC_Pickup
    ProbeBehabiour --> |variable| InteractProbe
    ProbeBehabiour --> |variable| DataList
    ProbeBehabiour --> |variable| bool
    ProbeBehabiour --> |variable| string
    ProbeBehabiour --> |variable| AudioSource
    ProbeBehabiour --> |variable| AudioClip
    ProbetaSnap --> |variable| bool
    ProbetaSnap --> |variable| GameObject
    ProbetaSnap --> |variable| VRC_Pickup
    PulidoraScript --> |variable| bool
    PulidoraScript --> |variable| float
    PulidoraScript --> |variable| TextMeshProUGUI
    PulidoraScript --> |variable| AudioSource
    PulidoraScript --> |variable| AudioClip
    SetKinematicFalseOnPickup --> |variable| bool
    SetKinematicFalseOnPickup --> |variable| VRCObjectSync
    SetKinematicFalseOnPickup --> |variable| Rigidbody
    SkyboxSetup --> |variable| Material
    SkyboxSetup --> |variable| DataDictionary
    SnowParticleFollowPlayer --> |variable| VRCObjectPool
    SnowParticleFollowPlayer --> |variable| VRCPlayerApi
    SnowParticlePooll --> |variable| VRCObjectPool
    TijerasBehabiour --> |variable| Animator
    TijerasBehabiour --> |variable| AudioSource
    TijerasBehabiour --> |variable| AudioClip
    TriggerPulidora --> |variable| float
    TriggerPulidora --> |variable| bool
    TriggerPulidora --> |variable| GameObject
    TriggerPulidora --> |variable| Vector3
    UpdatePreview --> |variable| GameObject
    UpdatePreview --> |variable| BorderColor
    UpdatePreview --> |variable| bool
    UpdatePreview --> |variable| float
    UpdatePreview --> |variable| int
    BoneFollower --> |variable| HumanBodyBones
    BoneFollower --> |variable| VRCPlayerApi
    BoneFollower --> |variable| bool
    InteractToggle --> |variable| GameObject[]
    PlayerModSetter --> |variable| float
    PlayerModSetter --> |variable| bool
    TrackingDataFollower --> |variable| VRCPlayerApi.TrackingDataType
    TrackingDataFollower --> |variable| VRCPlayerApi
    TrackingDataFollower --> |variable| bool
    WorldAudioSettings --> |variable| float
    WorldAudioSettings --> |variable| bool
    DemoDoor --> |variable| Animator
    DemoFirstPersonController --> |variable| Rigidbody
    DemoFirstPersonController --> |variable| CapsuleCollider
    DemoFirstPersonController --> |variable| bool
    DemoFirstPersonController --> |variable| Transform
    DemoFirstPersonController --> |variable| ControlType
    DemoFirstPersonController --> |variable| float
    DemoFirstPersonController --> |variable| GameObject
    GlobalToggleObject --> |variable| GameObject
    GlobalToggleObject --> |variable| bool
    MasterToggleObject --> |variable| GameObject
    MasterToggleObject --> |variable| bool
```
